language: go

go:
  - "1.13.x"
  - "1.14.x"
  - master

os:
  - linux
  - osx

dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic ./

# gobuild_args: -mod vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)
